//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon_V0.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirma
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Alan { get; set; }
        public string Yetkili { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adres { get; set; }
    }
}
